from random import randint
 
top100 = [
    '123456',
    '12345',
    '123456789',
    'password',
    'iloveyou',
    'princess',
    '1234567',
    'rockyou',
    '12345678',
    'abc123',
    'nicole',
    'daniel',
    'babygirl',
    'monkey',
    'lovely',
    'jessica',
    '654321',
    'michael',
    'ashley',
    'qwerty',
    '111111',
    'iloveu',
    '000000',
    'michelle',
    'tigger',
    'sunshine',
    'chocolate',
    'password1',
    'soccer',
    'anthony',
    'friends',
    'butterfly',
    'purple',
    'angel',
    'jordan',
    'liverpool',
    'justin',
    'loveme',
    'fuckyou',
    '123123',
    'football',
    'secret',
    'andrea',
    'carlos',
    'jennifer',
    'joshua',
    'bubbles',
    '1234567890',
    'superman',
    'hannah',
    'amanda',
    'loveyou',
    'pretty',
    'basketball',
    'andrew',
    'angels',
    'tweety',
    'flower',
    'playboy',
    'hello',
    'elizabeth',
    'hottie',
    'tinkerbell',
    'charlie',
    'samantha',
    'barbie',
    'chelsea',
    'lovers',
    'teamo',
    'jasmine',
    'brandon',
    '666666',
    'shadow',
    'melissa',
    'eminem',
    'matthew',
    'robert',
    'danielle',
    'forever',
    'family',
    'jonathan',
    '987654321',
    'computer',
    'whatever',
    'dragon',
    'vanessa',
    'cookie',
    'naruto',
    'summer',
    'sweety',
    'spongebob',
    'joseph',
    'junior',
    'softball',
    'taylor',
    'yellow',
    'daniela',
    'lauren',
    'mickey',
    'princesa']

def tough_salt():
    """
    replaces a random character in the password with a symbol
    """ 
    r = randint(1,100)
    password = top100[r]
    symbols = [40,41,60,62,91,93,123,125,37,43,45,47,61,92,34,39,44,46,58,59,63,95,32,33,35,36,38,42,63,94,124,126,64]
    length = len(symbols)-1
    rand1 = randint(1,length)
    salt = chr(symbols[rand1])
    pass_len = len(password)-1
    rand2 = randint(0,pass_len)
    randchr = password[rand2]
    honeyword = password.replace(randchr,salt)
    return honeyword

#print tough_salt()
